### PR TITLE
Add alias to front-matter for imported posts

### PR DESCRIPTION
**Pull request by dsolovay**
Adds alias field to front-matter, in format that hexo-generate-alias expects.  Fixes issue #4.

### CODE REVIEW

**Comment by dsolovay** [comment]
I didn't include logic to toggle this, as it would not have an effect if hexo-generate-alias was installed. However, let me know if you would like a way to enable or disable this, and whether this should be through a command line argument or a field in _config.yml.

**Comment by Xuanwo** [comment]
maybe we can add an argument in command line~
*BTW, nice gravatar*

**Comment by dsolovay** [comment]
Cool. Does this work?

    hexo migrate rss "source" [-alias]

**Comment by Xuanwo** [comment]
looks good !
When you are ready, please tell me and I will merge it.
And can you add a test for this so that we can use travis-ci to do unittest autometely ?

**Comment by dsolovay** [comment]
I've got the --alias working. I figured out that `--alias` gets converted to `args.alias`. The basic functionality is working now.

There are no tests currently for this module. I will work on adding some now.  

By the way, I am using VS Code, which has auto complete functionality if you include Type Script Definition files and add a jsconfig.json file (see https://code.visualstudio.com/docs/runtimes/nodejs). I was planning to update my **.gitignore** to suppress these changes, but let me know if you'd like to have them checked in instead.

**Comment by Xuanwo** [comment]
Wonderful work.

From my point of view, I think we shouldn't checked these files in the project because not everyone use VSCode to develop.

**Comment by dsolovay** [comment]
Sounds good. Okay to add these to **.gitignore**?

I've made initial progress on the test fixture. To make it a unit test, I've created a mock "hexo" object. I'll put some more work into this next weekend.  I've created a separate branch for this (https://github.com/dsolovay/hexo-migrator-rss/tree/add-tests), so it won't show up on this Pull Request until I have tests working.  Please take a look and let me know if this approach makes sense to you.

**Comment by Xuanwo** [comment]
Very nice workflow !
Whenever you are ready, make a pr to let me know !

**Comment by dsolovay** [comment]
Merged my test branch into master, so it is now in this pull request. Tests now cover both passing alias flag and not.

Had to refactor mainline code to allow testability:
* Split out migrator.js from index.js
* migrator.js now exports a functionthat can be called multiple times.

I also ran code manually with and without --alias flag to ensure that it worked after my refactoring.

**Comment by dsolovay** [comment]
I think this is ready to merge.  There are a few additional things I can do, but I might do these through future pull requests:
- [ ] Write tests to cover log info and warn messages.
- [ ] Modify REGEX by prepending a `^` so that it is less greedy. Right now it treats an XML string that contains a URL as a URL, making it impossible to test without making an external service call. (Is this an issue for travis?)  
- [ ] Add configuration so that travis-ci will run it (I haven't worked with travis, so feel free to jump in here.)

Note:  It's unfortunate we don't have isolation around `console.log`, as this means that certain tests emit log messages and it is impossible to test for these. But this would entail a change to the Hexo base architecture.

**Comment by Xuanwo** [comment]
LGTM :+1:

**Pull request merged**
